module.exports = {
  PRINT: 'PRINT',
  GET_COOKIE: 'GET_COOKIE',
  SET_COOKIE: 'SET_COOKIE',
  ERROR: 'ERROR',
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  GET_USER: 'GET_USER',
  UPDATE_USER: 'UPDATE_USER'
}
